name: CI
'on':
  workflow_dispatch:
  schedule:
    - cron: 5 2 */2 * *

jobs:
  init:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - name: Prep submit_here
        run: |
          (
          export LC_ALL=C
          umask 022

          prints() { sed -e '$a\' "$@"; }
          baseDir="./submit_here"
          edit_files=(exclude_for_all.txt exclude_for_mini_Lite_only.txt include_for_Pro_Xtra_only.txt include_for_all.txt)

          for file in "${edit_files[@]}"; do
          baseFile="$baseDir/$file"
          tempFile="$baseDir/click_me_to_edit/$file"

          if [[ ! -f "$tempFile" ]]; then
          touch "$tempFile"
          else
          if [ -s "$tempFile" ]; then
          newBase=$(prints "$tempFile" "$baseFile")
          prints <<<"$newBase" > "$baseFile"
          rm -f "$tempFile" && touch "$tempFile"
          fi
          fi
          done
          )
        shell: bash

      - name: Commit & Push
        uses: actions-js/push@master
        with:
          branch: master
          message: merge! submit_here
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Initiate update
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ci_PAT }}
          repository: ${{ secrets.target_repo }}
          event-type: Update
          client-payload: '{"success": true}'

      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 1

